name: gideon_aigbogun
description: "Flutter developer Portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  flutter_screenutil:
  auto_size_text:
  font_awesome_flutter:
  flutter_svg: ^2.0.7
  cached_network_image:
  google_fonts:
  shimmer:
  loading_animation_widget:
  url_launcher:


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
